// 화면 및 기능 흐름 확인용 샘플 데이터
// 실제 법령/SOP/과거 심의사례는 기관에서 추후 업로드 예정이며, 현재는 예시 데이터로 구성함
// 검토 과제(프로젝트/문서/검토결과 등)는 실사용을 위해 접수된 실제 건을 기본값으로 등록함

import type {
  ReviewProject,
  UploadedDocument,
  ReviewFinding,
  DocumentInconsistency,
  OpinionDraft,
  StaffMemo,
} from "../types/review";
import type { KnowledgeBaseItem } from "../types/knowledgeBase";

export const mockProjects: ReviewProject[] = [
  {
    id: "proj-1",
    receiptNo: "IRB-2026-012",
    title: "재태주수별 태반 무게 참고치 및 이상과 조직병리학적 진단의 연관성 분석",
    principalInvestigator: "홍길동",
    department: "조직병리팀",
    studyType: ["의무기록 연구"],
    reviewer: "백주환",
    receivedDate: "2026-06-05",
    status: "검토 중",
    memo: "",
    createdAt: "2026-06-05T09:00:00",
    updatedAt: "2026-06-05T09:00:00",
  },
];

export const mockDocuments: UploadedDocument[] = [
  {
    id: "doc-1",
    projectId: "proj-1",
    documentType: "연구계획서",
    fileName: "26-012_연구계획서(재태주수별 태반 무게 참고치 및 이상과 조직병리학적 진단의 연관성 분석)_V1.1_의견반영.pdf",
    fileUrl: "/project-documents/IRB-2026-012_연구계획서_V1.1.pdf",
    uploadedAt: "2026-06-05T09:00:00",
  },
];

export const mockFindings: ReviewFinding[] = [];

export const mockInconsistencies: DocumentInconsistency[] = [];

export const mockOpinionDrafts: OpinionDraft[] = [];

export const mockStaffMemos: StaffMemo[] = [];

export const mockKnowledgeBase: KnowledgeBaseItem[] = [
  {
    id: "kb-1",
    title: "생명윤리 및 안전에 관한 법률",
    type: "생명윤리법",
    version: "법률 제20327호",
    effectiveDate: "2024-08-21",
    applicableScope: "인간대상연구, 인체유래물연구 전반",
    keywords: ["개인정보", "동의", "인체유래물", "보관기간", "IRB"],
    summary: "인간대상연구 및 인체유래물연구 수행 시 준수해야 할 기본 법률로, 기관위원회(IRB) 설치·운영, 동의 절차, 개인정보 보호 원칙을 규정함.",
    content: "제16조(인간대상연구의 동의) 및 관련 조항 참고. 세부 조문은 첨부파일 확인.",
    relatedClause: "제3장 제16조~제18조",
    staffMemo: "동의서 필수 기재사항 검토 시 우선 참고",
    fileUrl: "/knowledge-base/kb-01-생명윤리법.pdf",
    active: true,
    remarks: "",
    createdAt: "2026-06-01T09:00:00",
    updatedAt: "2026-06-01T09:00:00",
  },
  {
    id: "kb-2",
    title: "보건의료데이터 활용 가이드라인",
    type: "개인정보 보호 관련 자료",
    version: "2024.01",
    effectiveDate: "2024-01-01",
    applicableScope: "개인정보(보건의료데이터)가 포함된 모든 연구",
    keywords: ["개인정보", "보건의료데이터", "가명처리", "보관", "폐기"],
    summary: "보건의료 데이터의 수집·이용·제공, 가명처리 및 안전관리에 관한 정부 합동 가이드라인.",
    content: "개인정보(보건의료데이터) 보관기간 경과 시 지체 없이 파기하여야 하며, 파기 방법을 구체적으로 명시하여야 함. 세부 기준은 첨부파일 참고.",
    relatedClause: "첨부파일 참고",
    staffMemo: "",
    fileUrl: "/knowledge-base/kb-10-보건의료데이터-활용가이드라인.pdf",
    active: true,
    remarks: "",
    createdAt: "2025-03-15T09:00:00",
    updatedAt: "2025-03-15T09:00:00",
  },
  {
    id: "kb-3",
    title: "연구계획서 표본수 산정 관련 식약처 가이드라인",
    type: "식약처 가이드라인",
    version: "1.2",
    effectiveDate: "2024-11-20",
    applicableScope: "체외진단의료기기 임상적 성능시험",
    keywords: ["표본수", "통계", "성능평가"],
    summary: "임상적 성능시험 시 목표 대상자 수 산정 방법 및 근거 제시 기준에 대한 가이드라인.",
    content: "목표 대상자 수는 통계적 방법 또는 참고문헌에 근거하여 산정하고, 산정 근거를 계획서에 기재하여야 함.",
    relatedClause: "Ⅲ. 임상적 성능시험계획서 작성 기준",
    staffMemo: "대상자 수 산정 근거 미기재 사례에서 반복 인용",
    fileUrl: "#",
    active: true,
    remarks: "",
    createdAt: "2024-11-20T09:00:00",
    updatedAt: "2024-11-20T09:00:00",
  },
  {
    id: "kb-4",
    title: "이해상충관리 표준운영지침(SOP)",
    type: "기관 SOP",
    version: "3.0",
    effectiveDate: "2026-01-01",
    applicableScope: "전체 연구자",
    keywords: ["이해상충", "서약서", "연구비"],
    summary: "연구자의 이해상충 신고 및 관리 절차를 규정한 기관 SOP.",
    content: "이해상충서약서는 최신 기관 서식(2026년 개정본)을 사용하여야 함.",
    relatedClause: "SOP-ETH-07",
    staffMemo: "서식 개정 이력 확인 시 참고",
    fileUrl: "#",
    active: true,
    remarks: "",
    createdAt: "2026-01-01T09:00:00",
    updatedAt: "2026-01-01T09:00:00",
  },
  {
    id: "kb-5",
    title: "잔여검체 활용 연구 관리지침(SOP)",
    type: "기관 SOP",
    version: "2.1",
    effectiveDate: "2025-09-01",
    applicableScope: "잔여검체 사용 연구",
    keywords: ["잔여검체", "사용범위", "폐기"],
    summary: "잔여검체 사용 시 사용 범위, 보관, 폐기에 관한 기관 내부 절차.",
    content: "잔여검체 사용 범위는 본 연구로 한정하며, 후속연구 활용 시 별도 동의 또는 심의를 받아야 함.",
    relatedClause: "SOP-BIO-04",
    staffMemo: "",
    fileUrl: "#",
    active: true,
    remarks: "",
    createdAt: "2025-09-01T09:00:00",
    updatedAt: "2025-09-01T09:00:00",
  },
  {
    id: "kb-6",
    title: "생명윤리 및 안전에 관한 법률 시행규칙",
    type: "시행규칙",
    version: "보건복지부령 제1048호",
    effectiveDate: "2024-08-21",
    applicableScope: "인간대상연구, 인체유래물연구 전반",
    keywords: ["검체", "보관기간", "서식", "인체유래물"],
    summary: "생명윤리법 및 시행령에서 위임한 세부사항(서식, 보관·폐기 절차 등)을 규정한 시행규칙.",
    content: "검체(인체유래물) 보관기간 및 폐기 방법은 계획서·동의서에 일관되게 명시하여야 함. 세부 조문은 첨부파일 참고.",
    relatedClause: "첨부파일 참고",
    staffMemo: "",
    fileUrl: "/knowledge-base/kb-03-생명윤리법-시행규칙.pdf",
    active: true,
    remarks: "",
    createdAt: "2025-07-01T09:00:00",
    updatedAt: "2025-07-01T09:00:00",
  },
  {
    id: "kb-7",
    title: "연구결과보고서 제출 관련 표준 보완문구",
    type: "표준 보완문구",
    version: "1.0",
    effectiveDate: "2025-01-10",
    applicableScope: "전체 연구 유형",
    keywords: ["결과보고서", "제출시점", "표준문구"],
    summary: "결과보고서 제출 시점 미기재 시 사용할 수 있는 표준 보완 요청 문구 모음.",
    content: "\"연구 종료 후 결과보고서 제출 예정 시점을 명시하여 주시기 바랍니다.\"",
    relatedClause: "-",
    staffMemo: "",
    fileUrl: "#",
    active: true,
    remarks: "",
    createdAt: "2025-01-10T09:00:00",
    updatedAt: "2025-01-10T09:00:00",
  },
  {
    id: "kb-9",
    title: "생명윤리 및 안전에 관한 법률 시행령",
    type: "시행규칙",
    version: "대통령령 제34747호",
    effectiveDate: "2024-07-23",
    applicableScope: "인간대상연구, 인체유래물연구 전반",
    keywords: ["생명윤리법", "시행령"],
    summary: "생명윤리 및 안전에 관한 법률에서 위임한 사항과 시행에 필요한 세부사항을 규정한 시행령.",
    content: "세부 조문은 첨부파일 참고.",
    relatedClause: "첨부파일 참고",
    staffMemo: "",
    fileUrl: "/knowledge-base/kb-02-생명윤리법-시행령.pdf",
    active: true,
    remarks: "",
    createdAt: "2026-07-06T09:00:00",
    updatedAt: "2026-07-06T09:00:00",
  },
  {
    id: "kb-10",
    title: "[별표 2] 임상적 성능시험 기본문서의 종류, 목적 및 문서별 보관책임자",
    type: "시행규칙",
    version: "체외진단의료기기 임상적 성능시험 실시 및 관리에 관한 규정 [별표 2]",
    effectiveDate: "",
    applicableScope: "체외진단의료기기 임상적 성능시험",
    keywords: ["임상적 성능시험", "기본문서", "보관책임자", "문서보관"],
    summary: "임상적 성능시험 수행 시 작성·보관해야 하는 기본문서의 종류, 목적 및 문서별 보관책임자를 정리한 별표.",
    content: "문서 종류별 보관책임자 및 보관기간은 첨부파일 참고.",
    relatedClause: "첨부파일 참고",
    staffMemo: "",
    fileUrl: "/knowledge-base/kb-04-임상적성능시험-기본문서-별표2.pdf",
    active: true,
    remarks: "",
    createdAt: "2026-07-06T09:00:00",
    updatedAt: "2026-07-06T09:00:00",
  },
  {
    id: "kb-11",
    title: "체외진단의료기기 임상적 성능시험 가이드라인",
    type: "식약처 가이드라인",
    version: "민원인 안내서 (2020.11.26)",
    effectiveDate: "2020-11-26",
    applicableScope: "체외진단의료기기 임상적 성능시험",
    keywords: ["체외진단의료기기", "임상적 성능시험", "가이드라인"],
    summary: "체외진단의료기기 임상적 성능시험계획서 작성 및 수행 전반에 대한 식약처 민원인 안내서.",
    content: "임상적 성능시험계획서 작성 기준 및 절차는 첨부파일 참고.",
    relatedClause: "첨부파일 참고",
    staffMemo: "",
    fileUrl: "/knowledge-base/kb-05-체외진단기기-임상적성능시험-가이드라인.pdf",
    active: true,
    remarks: "",
    createdAt: "2026-07-06T09:00:00",
    updatedAt: "2026-07-06T09:00:00",
  },
  {
    id: "kb-12",
    title: "체외진단의료기기 임상적 성능시험 시 일반적 고려사항",
    type: "식약처 가이드라인",
    version: "민원인 안내서 (2023.12)",
    effectiveDate: "2023-12-01",
    applicableScope: "체외진단의료기기 임상적 성능시험",
    keywords: ["임상적 성능시험", "고려사항", "식약처"],
    summary: "체외진단의료기기 임상적 성능시험 수행 시 고려해야 할 일반 사항에 대한 식약처 민원인 안내서.",
    content: "세부 고려사항은 첨부파일 참고.",
    relatedClause: "첨부파일 참고",
    staffMemo: "",
    fileUrl: "/knowledge-base/kb-06-임상적성능시험-일반적고려사항.pdf",
    active: true,
    remarks: "",
    createdAt: "2026-07-06T09:00:00",
    updatedAt: "2026-07-06T09:00:00",
  },
  {
    id: "kb-13",
    title: "체외진단의료기기 임상적 성능시험기관 지정 및 종사자 교육에 관한 규정",
    type: "시행규칙",
    version: "식약처 고시 제2020-32호",
    effectiveDate: "",
    applicableScope: "체외진단의료기기 임상적 성능시험기관",
    keywords: ["임상적 성능시험기관", "지정", "종사자 교육", "실태조사"],
    summary: "임상적 성능시험기관의 지정 요건 및 종사자 교육, 실태조사평가표에 관한 식약처 제정고시.",
    content: "지정 요건 및 실태조사평가표는 첨부파일 참고.",
    relatedClause: "첨부파일 참고",
    staffMemo: "",
    fileUrl: "/knowledge-base/kb-07-임상적성능시험기관-지정-종사자교육-고시.pdf",
    active: true,
    remarks: "",
    createdAt: "2026-07-06T09:00:00",
    updatedAt: "2026-07-06T09:00:00",
  },
  {
    id: "kb-14",
    title: "체외진단의료기기 허가신고심사 등에 관한 규정 해설서",
    type: "식약처 가이드라인",
    version: "해설서 (2020.09.28)",
    effectiveDate: "2020-09-28",
    applicableScope: "체외진단의료기기 허가·신고·심사",
    keywords: ["허가", "신고", "심사", "해설서"],
    summary: "체외진단의료기기 허가·신고·심사 등에 관한 규정을 조문별로 해설한 식약처 해설서.",
    content: "조문별 해설은 첨부파일 참고.",
    relatedClause: "첨부파일 참고",
    staffMemo: "",
    fileUrl: "/knowledge-base/kb-08-체외진단기기-허가신고심사-해설서.pdf",
    active: true,
    remarks: "",
    createdAt: "2026-07-06T09:00:00",
    updatedAt: "2026-07-06T09:00:00",
  },
  {
    id: "kb-15",
    title: "IRB 행정 및 HRPP 운영 매뉴얼",
    type: "기타",
    version: "2020년판",
    effectiveDate: "2020-01-01",
    applicableScope: "IRB 행정 업무 전반",
    keywords: ["IRB", "HRPP", "행정", "운영매뉴얼"],
    summary: "IRB 행정 업무 및 HRPP(인간연구보호프로그램) 운영 전반에 대한 참고 매뉴얼(외부 발간).",
    content: "IRB 행정 절차 및 HRPP 운영 기준은 첨부파일 참고.",
    relatedClause: "첨부파일 참고",
    staffMemo: "기관 자체 SOP가 아닌 외부(KAIRB) 발간 참고자료임",
    fileUrl: "/knowledge-base/kb-09-KAIRB-IRB행정-HRPP운영매뉴얼.pdf",
    active: true,
    remarks: "KAIRB(한국IRB협의체) 발간 자료",
    createdAt: "2026-07-06T09:00:00",
    updatedAt: "2026-07-06T09:00:00",
  },
  {
    id: "kb-16",
    title: "체외진단의료기기 임상적 성능시험 실시 및 관리 안내서",
    type: "식약처 가이드라인",
    version: "안내서",
    effectiveDate: "",
    applicableScope: "체외진단의료기기 임상적 성능시험",
    keywords: ["임상적 성능시험", "실시", "관리", "안내서"],
    summary: "체외진단의료기기 임상적 성능시험의 실시 및 관리 전반에 대한 안내서.",
    content: "실시 및 관리 절차는 첨부파일 참고.",
    relatedClause: "첨부파일 참고",
    staffMemo: "",
    fileUrl: "/knowledge-base/kb-11-임상적성능시험-실시및관리-안내서.pdf",
    active: true,
    remarks: "",
    createdAt: "2026-07-06T09:00:00",
    updatedAt: "2026-07-06T09:00:00",
  },
];
